- ansible/group_vars/all
- ansible/idr-deployment.yml
- ansible/idr-provision.yml
- ansible/roles/docker-dns-client/tasks/main.yml
- ansible/roles/docker-dns-client/templates/systemd-docker-registrator.j2
- ansible/roles/docker-dns-server/tasks/main.yml
- ansible/roles/docker-dns-server/templates/systemd-docker-etcd.j2
- ansible/roles/docker-dns-server/templates/systemd-docker-skydns.j2
- ansible/roles/docker-storage/README.md
- ansible/roles/docker-storage/meta/main.yml
- ansible/roles/docker-storage/tasks/main.yml
- ansible/roles/docker/README.md
- ansible/roles/docker/files/docker-storage-setup
- ansible/roles/docker/handlers/main.yml
- ansible/roles/docker/tasks/main.yml
- ansible/roles/docker/templates/docker-network.j2
- ansible/roles/docker/templates/docker-storage.j2
- ansible/roles/lvm-partition/README.md
- ansible/roles/lvm-partition/defaults/main.yml
- ansible/roles/lvm-partition/tasks/main.yml
- ansible/roles/network/handlers/main.yml
- ansible/roles/network/tasks/main.yml
- ansible/roles/network/templates/etc-sysconfig-network-scripts-ifcfg.j2
- ansible/roles/samba-client/README.md
- ansible/roles/samba-client/tasks/main.yml
Includes
- docker-storage for setting up the docker thin partitions
- docker for setting up docker including groups
- lvm-partition as a generic role for creating any LVM storage partition
- role for installing samba-clients
Also separate playbooks for provisioning (setting up hardware) and deploying (everything else which doesn't involve hardware configuration)
Note the generic `lvm-partition` role could be used to replace the `jenkinsslave-storage` role in a future PR.
> Docker node roles

- ansible/idr-deployment.yml
- ansible/roles/docker/tasks/main.yml
- ansible/roles/omero-basedeps/tasks/main.yml
- ansible/roles/samba-client/tasks/main.yml
- ansible/roles/versioncontrol-utils/README.md
- ansible/roles/versioncontrol-utils/tasks/main.yml
Add `versioncontrol-utils` role for servers which need to manage code but are not full development/build servers. Also changed `yum state` from `latest` to `present` to avoid upgrading some packages such as docker without warning. If there's no objections I'll do the same for all other roles in a future PR.
Tested with `idr-deployment.yml` (i.e. I ran the playbook and applied the changes).
> Install git on IDR nodes

- ansible/README.md
- ansible/ci-deployment.yml
- ansible/qa-web-deployment.yml
This PR defines a new playbook for deploying nodes used for the Web applications (registry, QA). Depending on their usage (staging/production), they can be used with/without `ci-provision.yml` to hook them to Jenkins. /cc @kennethgillen
> QA Web playbook

- ansible/roles/nginx-ssl-selfsigned/README.md
- ansible/roles/nginx-ssl-selfsigned/defaults/main.yml
- ansible/roles/nginx-ssl-selfsigned/tasks/main.yml
This is useful for testing https internally.
> Add role for creating nginx self-signed certificates

- ansible/ci-provision.yml
- ansible/idr-deployment.yml
- ansible/idr-provision.yml
- ansible/roles/docker-dns-client/templates/systemd-docker-registrator.j2
- ansible/roles/docker/defaults/main.yml
- ansible/roles/docker/tasks/advanced-upstream.yml
- ansible/roles/docker/tasks/docker-centos.yml
- ansible/roles/docker/templates/docker-engine.j2
- ansible/roles/network/templates/etc-sysconfig-network-scripts-ifcfg.j2
- ansible/roles/server-swap/README.md
- ansible/roles/server-swap/defaults/main.yml
- ansible/roles/server-swap/tasks/main.yml
- Fixes an error found in #32 when using the non-default storage config.
Rebased and updated: 2015-12-10:
- Allows additional parameters to be passed to the docker daemon, for example to work around strange incompatibilities between systemd/cgroups/docker which may occur when using the upstream version. E.g https://github.com/docker/docker/issues/16256 (though the bug observed is different)
- Adds workaround for registrator sometimes failing to start
Update 2015-12-11
- Include #40 Attempt to reduce swap load http://serverfault.com/a/692515
> systemctl daemon-reload, other docker fixes

- ansible/ci-provision.yml
Updating this repo with the current state of docker on `docker-dev-hosts`
> Create docker-dev-hosts group (like prod, but with dns)

- ansible/roles/network/README.md
- ansible/roles/network/handlers/main.yml
- ansible/roles/network/tasks/main.yml
- ansible/roles/network/templates/etc-sysconfig-network-scripts-ifcfg-disabled.j2
- ansible/roles/network/templates/etc-sysconfig-network-scripts-ifcfg.j2
Support configuration of bonded interfaces, see README for an example.
- `network_disable_ifaces` is to explicity create NIC config files to disable a NIC
- `network_delete_ifaces` is to delete unwanted `ifcfg-.*` files, for instance kickstarting a node may create an interface name which doesn't match the required naming.
> Network bonding, delete/disable unused NICs

- ansible/idr-provision.yml
- ansible/roles/docker/README.md
- ansible/roles/docker/defaults/main.yml
Small cleanup- make some mandatory vars optional.
Note `ansible/idr-provision.yml` group `idr-docker` is out of date (uses the old docker role) so probably best to ignore it.
> Docker default filesystems

- ansible/ci-docker-dev-hosts.yml
- ansible/ci-docker-prod-hosts.yml
- ansible/ci-initial.yml
- ansible/ci-jenkins-linux.yml
- ansible/ci-provision.yml
- ansible/idr-provision.yml
- ansible/roles/docker/README.md
- ansible/roles/docker/defaults/main.yml
- ansible/roles/network/tasks/main.yml
- `ci-provision.yml` is now the run-everything playbook, and is made up of individual playbooks named after groups, which can be run independently. (Remember a host can be a member of multiple groups, so this allows you to manage one piece of "functionality" of a node)
- You can run `ci-provision.yml` with `--limit` to provision a new node, but if you are doing any hardware configuration it's a good idea to reboot in between. E.g. If you are reconfiguring the network run `ci-initial.yml` first, reboot, then run your other playbook, or just run the parent `ci-provision.yml` since Ansible is idempotent.
Note: I've started doing something similar with the IDR playbooks, but it made more sense to sort out ci-docker first. Also once everyone's happy with a workflow I'll add some docs …
> Start refactoring CI playbooks

- ansible/idr-samba-hosts.yml
- ansible/roles/active-directory-join/README.md
- ansible/roles/active-directory-join/handlers/main.yml
- ansible/roles/active-directory-join/tasks/main.yml
- ansible/roles/active-directory-join/templates/krb5-conf.j2
- ansible/roles/active-directory-join/templates/security-access-conf.j2
- ansible/roles/active-directory-join/templates/sssd-sssd-conf.j2
- ansible/roles/active-directory-samba-share/README.md
- ansible/roles/active-directory-samba-share/defaults/main.yml
- ansible/roles/active-directory-samba-share/handlers/main.yml
- ansible/roles/active-directory-samba-share/tasks/main.yml
- ansible/roles/active-directory-samba-share/templates/samba-smb-conf.j2
`active-directory-join`: Take a clean CentOS 7 VM, run this with a host-vars file including AD username/password, and you should be able to ssh in with ldap.
`active-directory-samba-share`: See the readme for an example config for setting up samba shares. This is not dependent on `active-directory-join`, but it does assume AD has already been configured.
Docker might work too (untested).
> Add roles for connecting a VM to active directory, and for creating samba shares

- ansible/.gitignore
- ansible/Vagrantfile
- ansible/test.yml
Used this infrastructure to test https://github.com/openmicroscopy/infrastructure/pull/57
First run showed:
Second run showed:
> Vagrant-based tests for infrastructure

- ansible/idr-analysis.yml
- ansible/idr-sudoers.yml
- ansible/roles/analysis-tools/README.md
- ansible/roles/analysis-tools/meta/main.yml
- ansible/roles/analysis-tools/tasks/main.yml
- ansible/roles/sudoers/README.md
- ansible/roles/sudoers/tasks/main.yml
- ansible/roles/sudoers/templates/sudoers-individual_commands.j2
`sudoers` should do the job for now, though there's room for improvement.
`analysis-tools` just installs `parallel` for now, but should be extended if other tools are required.
`idr-analysis.yml` playbook includes the two roles above, plus samba-client to ensure `smbclient` and `mount.cifs` are installed.
> Initial role for managing sudoers, role for analysis tools, idr-analysis playbook

- ansible/roles/network/tasks/main.yml
70dfcf261b531feed8751f5e57b82b709bba3b6e Fixes an error where if an item was not skipped `item.skip` field may not exist. I don't know whether this is an error I missed before, or whether its a change in Ansible.
The remaining commits fix deprecation warnings for this role only.
> Network check bonding skip

- ansible/README-os-idr.md
- ansible/os-create.yml
- ansible/os-idr-ebi.yml
- ansible/os-idr-uod.yml
- ansible/os-omero.yml
- ansible/vars/test-overrides.yml
- All volumes now use the raw disk without partitions (`vdb`)
- group_vars have been moved to the `os-idr` group, so that they can be copied and overriden easily
- See updated README
> Use vdb for omero volume, support custom hostgroups for different environments

- ansible/idr-playbooks/idr-dundee-nfs.yml
- ansible/idrsystems-deployment.yml
- ansible/idrsystems-playbooks/idr-docker-localstorage.yml
- ansible/idrsystems-playbooks/idr-gpfs-client.yml
- ansible/idrsystems-playbooks/idr-nfs-clients.yml
- ansible/idrsystems-playbooks/idr-nfs-hosts.yml
- ansible/idrsystems-playbooks/idr-upgrade.yml
- ansible/roles/docker/README.md
- ansible/roles/docker/defaults/main.yml
- ansible/roles/docker/tasks/main.yml
- ansible/roles/docker/templates/docker-repo.j2
- ansible/roles/gpfs/README.md
- ansible/roles/gpfs/defaults/main.yml
- ansible/roles/gpfs/tasks/gpfs-configure.yml
- ansible/roles/gpfs/tasks/gpfs-repoinstall.yml
- ansible/roles/gpfs/tasks/main.yml
- ansible/roles/gpfs/templates/gpfs-repo.j2
- ansible/roles/nfs-ganesha-share/README.md
- ansible/roles/nfs-ganesha-share/defaults/main.yml
- ansible/roles/nfs-ganesha-share/handlers/main.yml
- ansible/roles/nfs-ganesha-share/tasks/main.yml
- ansible/roles/nfs-ganesha-share/templates/ganesha-conf.j2
- ansible/roles/nfs-mount/README.md
- ansible/roles/nfs-mount/defaults/main.yml
- ansible/roles/nfs-mount/tasks/main.yml
- ansible/roles/upgrade-distpackages/README.md
- ansible/roles/upgrade-distpackages/defaults/main.yml
- ansible/roles/upgrade-distpackages/tasks/main.yml
Multiple changes related to setting up some new servers, and re-imaging the broken GPFS/NFS server.
- Option added to use a different repo, e.g. `testing` to install docker release candidates
- Fixed variable quoting warning
- Added a simpler alternative to the current build and install steps. If you have access to a GPFS yum repository, and you don't mind installing a compiler tool-chain on your server, you can install the base RPMs from the repo, compile the kernel module on the server, and install it
- The `nfs-share` role uses the built-in kernel NFS server, however this has problems when serving GPFS: https://access.redhat.com/solutions/1553943. nfs-ganesha is a user-mode server which may work better.
- Note that this is the default `VFS` module, not the specialised `GPFS` …
> New docker nodes, add ganesha NFS, update GPFS

- ansible/Vagrantfile
- ansible/os-uod-docker.yml
- ansible/os-uod-web.yml
- ansible/training-server.yml
- ansible/uod-docker.yml
- ansible/uod-web.yml
Few cleanup commits as well as a few new playbooks for getting new production services on openstack:
* `training-server` migrated from management_tools (thanks @kennethgillen!)
* playbooks for production docker containers
* playbooks for development web server
> Prod openstack (infra)

- ansible/roles/gpfs/README.md
- docs/storage/gpfs.md
`ansible/roles/gpfs/README.md` now only contains information directly related to the `gpfs` role, all other information is included in the more general document `/docs/storage/gpfs.md`
> Rearrange GPFS docs

- README.md
As Ansible 2.0 has been released for a long time, there is no obvious reason not to use a pip-installed Ansible. This also simplifies the installation instructions.
> Update Ansible installation instructions

- ansible/idrsystems-deployment.yml
- ansible/idrsystems-playbooks/idr-docker-localstorage.yml
- ansible/idrsystems-playbooks/idr-gpfs-scratch.yml
In conjunction with the private config file this:
- symlinks `/home/idr-scratch` into gpfs. The intention is to make it clearer that the main gpfs directory can be mounted read-only in docker and to have `/home/idr-scratch` mounted in docker read-write.
- adds the `sudoers` role. This requires an additional configuration file to have an effect, and could arguably go into a common-top-level playbook for all servers.
> Add gpfs symlinks, Add sudoers

- ansible/idrsystems-deployment.yml
- ansible/idrsystems-playbooks/idr-docker.yml
I need to split up the configuration of the `idr-docker-localstorage` group into two (the same variable needs to take different values on different nodes), and now that the old docker nodes have been re-imaged it's a good time to rename this group to just `idr-docker`
> Rename idr-docker-localstorage to idr-docker

- ansible/roles/ice/tasks/main.yml
- ansible/roles/ice/vars/ice-3.6.yml
Previously this would pip-install `ice 3.6.1`. It should now install the most recent in the `3.6` series.
> pip install the latest ice 3.6.x

- ansible/roles/omero-server/README.md
- ansible/roles/omero-server/tasks/main.yml
- ansible/roles/omero-server/tasks/omero-user.yml
- ansible/training-server.yml
- Fixes the lack of idempotency when modifying `~omero/.bashrc`: closes https://github.com/openmicroscopy/infrastructure/issues/77
- The `omero-server` role takes into account the value of `ice_version` from `roles/ice` (currently still `3.5`, should it be bumped to `3.6`?)
- Remove a harmless (though distracting) red ignored error message when checking for the existing version of a non-existent server
- `training-server.yml` updated to take account of the above
> Omero server cleanups

- ansible/ansible.cfg
- ansible/ci-deployment.yml
- ansible/inventory/README.md
- ansible/os-uod-docker.yml
- ansible/os-uod-slave.yml
- ansible/roles/basedeps/tasks/main.yml
- ansible/roles/ice/vars/ice-3.6.yml
- ansible/roles/jenkinsslave/defaults/main.yml
- ansible/roles/jenkinsslave/meta/main.yml
- ansible/roles/jenkinsslave/tasks/main.yml
- ansible/roles/jenkinsslave/tasks/setup_virtualenv.yml
- ansible/roles/omero-runtime/tasks/main.yml
- ansible/roles/omero-web-runtime/defaults/main.yml
- ansible/roles/omero-web-runtime/tasks/main.yml
- ansible/roles/postgresql/tasks/databases.yml
- ansible/uod-slave.yml
This PR improve ci slave deployment:
- add epel repo
- add hudson to sudoers
- add omero postgres user and allow creating DB
- define `management_tools/ansible/ci/ci-test-hosts`:
```
[ci-jenkins-linux]
ip1 (server)
ip2 (web)
[ci-omero]
ip1
[ci-omero-web]
ip2
```
- clone this
- cd infrastructure/ansible
- run playbook
```
ansible-playbook -i ../../management_tools/ansible/ci/ci-test-hosts  -vv -u centos ci-deployment.yml
```
Jenkins authorized key is set in https://github.com/openmicroscopy/management_tools/blob/master/ansible/ci/group_vars/ci-jenkins-linux#L8. make sure appropriate `SSH Username with private key` is chosen to Jenkins before connecting to the node.
see http://10.0.51.148/
Todo:
- no strategy for storing snoopy ssh keys
> improve ci deployment

- ansible/roles/omero-build/tasks/main.yml
While migrating https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-breaking-build/602/ to seabass post provision/deployment, I realized that our code has been tested with FindBugs 3.0.0 and FindBugs 3.0.1 is not supported yet. /cc @kennethgillen
> Downgrade Findbugs version to 3.0.0

- ansible/devspace-runtime.yml
- ansible/devspace.yml
- ansible/os-devspace.yml
- ansible/roles/devspace/defaults/main.yml
- ansible/roles/devspace/tasks/main.yml
This PR shows how to deploy and manage devspace using ansible and docker_service
- brief understanding of ansible http://docs.ansible.com/ansible/intro_getting_started.html or tutorial by @joshmoore 
- inventory http://docs.ansible.com/ansible/intro_inventory.html
- playbook http://docs.ansible.com/ansible/playbooks.html
- access to openstack tenancy
- own ssh key set in openstack tenancy, that name will be used as `vm_key_name`
- `openrc.sh` http://docs.openstack.org/user-guide/common/cli-set-environment-variables-using-openstack-rc.html
- snoopy ssh key and gitconfig (* to be discussed
To run devspace run following on the client machine:
- install virtualenv and pip prerequisites:
```
$ virtualenv dev
$ source dev/bin/activate
(dev) $ pip install ansible
(dev) $ pip install shade
(dev) …
```
> devspace playbook

- README.md
- ansible/ansible.cfg
Most of the options included here are for working with
dozens of servers at once time. Also, they assume a
location for your local inventory (../../ansible/inventory)
which simplifies use for the OME team.
> Update ansible.cfg for performance

- ansible/Vagrantfile
The `idr-*` ansible config was previously global, including `ansible.limit = "idr"`. This PR makes it local to just the idr-* nodes now. `vagrant up` should now bring up all nodes.
Current HEAD is broken so tested against c5c56e34563b6dd3e3218b9176ba10ef21b235bd
You might be able to find a more recent working version.
> Fix Vagrantfile so `vagrant up` brings up all nodes

- ansible/ansible.cfg
They're both useful but profiling adds extra output which obscures the rest of the ansible-playbook output, and `pipelining` is causing problems at the moment. These should be investigated later.
> Revert some performance improvement changes to ansible.cfg

- ansible/ansible.cfg
- ansible/plugins/callback/error_if_no_hosts_match.py
This adds a callback so that Ansible will set a non-zero exit code if a playbook was run but no hosts match.  This is useful when running ansible-playbook automatically. For example, when running vagrant to test the Vagrantfile if there is a mismatch between the hosts expect by the playbook and the hosts in the Vagrantfile ansible would normally not care.
If you think this is inappropriate it could go into an alternative `ansible.cfg` which is used only by `vagrant` (e.g. set `ANSIBLE_CONFIG`)
> Return non-zero error code if no hosts match

- ansible/roles/omero-build/defaults/main.yml
- ansible/roles/omero-build/tasks/main.yml
Noticed by @jburel during OMERO 5.2.6 release process. This should add a conditional step in the `omero-build` role to install `exe4j` license from a string.
> Exe4j: license

- ansible/roles/omero-server/defaults/main.yml
- ansible/roles/omero-server/tasks/main.yml
Treat the config.omero file specified by `omero_prestart_file` as a Jinja2 template. In practice this means anything in `{{ ... }}` will be transformed, otherwise it should be the same as the previous behaviour.
Motivation: Allow most configuration to be public whilst having a placeholder for sensitive configuration information. For example if the file contains: `config set omero.web.public.password {{ secret_password | default("omero") }}` this will be interpreted as
- `config set omero.web.public.password omero` by default
- `config set omero.web.public.password <secret_password>` if the variable `secret_password` is defined
> Change omero_prestart_file to a j2 template

- ansible/roles/docker-tools/README.md
- ansible/roles/docker-tools/tasks/main.yml
- ansible/test.yml
I need this for the IDR so created this role based on https://github.com/openmicroscopy/infrastructure/blob/master/ansible/roles/devspace/tasks/main.yml
If everyone's happy I'll update `roles/devspace` to depend on this.
/cc @aleksandra-tarkowska
> Add docker-tools role to install docker-compose globally

- ansible/roles/omero-build/defaults/main.yml
This works around an issue that has appeared a few times recently. I also failed to properly set this from the command-line with `-e spacewalk=True` (i.e. my tasks were still not activating)
Likely a rethink is needed of the spacewalk boolean. Perhaps it can be wrapped as an entire role.
> omero-build: add defaults to fix spacewalk issue

- ansible/Vagrantfile
- ansible/roles/postgresql/README.md
- ansible/roles/postgresql/tasks/databases.yml
- ansible/test.yml
Reverts the change to the `postgres` role from https://github.com/openmicroscopy/infrastructure/commit/cd92c3d2bfe7f52bb65d0f822db30c9669d8fd74#diff-5c81521b75eb3f697f59fd8f1d245303 and replaces it with a new optional parameter. Also adds a vagrant test including some asserts.
> Postgres revert role privileges

- ansible/devspace.yml
- ansible/roles/devspace/defaults/main.yml
- ansible/roles/devspace/tasks/devspace-install.yml
This should use the last tag (and make the corresponding changes).
This PR is currently redeployed on the BF 5.3 devspace with a minimal host_var file
````
docker_use_ipv4_nic_mtu: True
omero_branch: dev_5_3
````
> Bump devspace role version to 0.3.1

- ansible/roles/nginx-proxy/README.md
- ansible/roles/nginx-proxy/templates/nginx-confd-proxy.j2
Follow up to https://github.com/openmicroscopy/infrastructure/pull/140. Adds a workaround for webproxy connections where the `Host` header seems to be incorrect, even though it's already set in the `server` scope.
> Work around websocket proxy issue: set Host header

- ansible/idr-playbooks/files/IDR-OMERO-52-omero.j2
- ansible/roles/omero-web-runtime/tasks/main.yml
When using redis we have to use newer supported package https://trello.com/c/GIJQA0kg/177-redis-out-of-experimental
> upgrade django-redis

- ansible/devspace.yml
- ansible/roles/devspace/defaults/main.yml
- ansible/roles/devspace/handlers/main.yml
- ansible/roles/devspace/tasks/devspace-install.yml
- ansible/roles/devspace/tasks/devspace-runtime.yml
This PR renams vars and fixed jenkins url to match ip (that value is used by testng)
Test:
with https://github.com/openmicroscopy/devspace/pull/52
- default:
- vars:
```
openstack_ip: IP
omero_branch: develop
snoopy_dir_path: "/path/to/snoopy"
git_repo: "https://github.com/aleksandra-tarkowska/devspace.git"
version: "customization"
```
- run:
```
$ ansible-playbook os-devspace.yml -e vm_name=devspace-test -e vm_key_name=your_key
$ ansible-playbook -l devspace-test -u centos devspace.yml 
```
> cleanup devspace

- ansible/Vagrantfile
- ansible/roles/nginx-proxy/meta/main.yml
- ansible/roles/nginx-proxy/tasks/main.yml
- ansible/roles/selinux-utils/README.md
- ansible/roles/selinux-utils/tasks/main.yml
- ansible/test.yml
There are several roles which require conditional tasks depending on whether SELinux is enabled or not. Furthermore Ansible has some SELinux package dependencies which aren't always installed by default. This role abstracts away all that complexity:
- Sets a host-variable `selinux_enabled`: `True`/`False`, this can be checked in other roles or playbooks
- If SELinux is enabled or permissive installs SELinux dependencies required by Ansible, otherwise it doesn't
- See the README for details.
This also modifies the `nginx-proxy` role to use this new role. Other roles can be updated in separate PRs.
> New role to hide SELinux issues

- ansible/roles/upgrade-distpackages/tasks/main.yml
- Force a yum cache refresh. Today's patching showed that the cache isn't always updated before instaling updates.
> System upgrade fixes

- ansible/Vagrantfile
- ansible/ci-deployment.yml
- ansible/roles/python-devel/tasks/main.yml
- ansible/roles/sphinx-build/README.md
- ansible/roles/sphinx-build/meta/main.yml
- ansible/roles/sphinx-build/tasks/main.yml
- ansible/test.yml
This is a minimal port of the changes proposed https://github.com/openmicroscopy/infrastructure/pull/20 in the context of the upcoming Bio-Formats 5.3.0-m1 release preparation.
This PR puts the minimal requirements into place for documentation nodes, i.e. installing Sphinx as a dependency. As discussed previously, Sphinx is installed globally instead of within a virtual environment to allow it to be consumed by the Jenkins Ant targets which cannot activate a virtual environment. It also applies the policy of dropping the PDF in favor of ZIPs of the HTML and removes the `texlive` step from the `ci-deployment` playbook. /cc @jburel
> Sphinx build role

- ansible/roles/nginx/tasks/main.yml
I updated VirtualBox and was unable to download http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm when running vagrant. I've no idea if it's a VirtualBox/OS X problem, or a change by nginx.org, but using `https` instead seemed to fix it. In any case using `https` should be more secure.
> Download nginx from https location

- ansible/roles/docker/README.md
- ansible/roles/docker/defaults/main.yml
- ansible/roles/docker/tasks/main.yml
As @aleksandra-tarkowska discovered in #149 Ansible 2.2 drops the previously deprecated usage of undefined vars. This fixes the docker role.
Closes #160
> Fix deprecated usage of undefined docker var

- ansible/Vagrantfile
Allow you to test vagrant boxes on openstack, useful if you upgrade VirtualBox and discover it's broken.
```
vagrant plugin install vagrant-openstack-provider
source openrc.sh
vagrant up --provider openstack BOXNAME ...
```
> Add openstack provider to Vagrantfile

- ansible/roles/openstack-volume-storage/README.md
- ansible/roles/openstack-volume-storage/library/os_volume_ansible23.py
- ansible/roles/openstack-volume-storage/tasks/main.yml
https://github.com/ansible/ansible-modules-core/pull/5176 enables Ansible to clone openstack volumes, which is quicker than creating a volume from a snapshot. It is targeted for Ansible 2.3, but in the meantime this PR bundles it in the `openstack-volume-storage` role so we can take advantage of it in the IDR. This should be reverted assuming Ansible 2.3 is released with the above feature.
It should be possible to override a module of the same name, but I couldn't get it to work.
> OpenStack volume ansible 2.3 features

- ansible/Vagrantfile
Replace 8 identical server definitions with a loop. Removed Ansible verbose output so it's easier to check the output, there should be no other change in behaviour or usage of vagrant.
> Remove redundancy in Vagrantfile test.yml definitions

- ansible/inventory/openstack-private.py
- ansible/inventory/openstack.py
`OS_CLOUD` is one of the standard os-client-config environment variables that can be used to select a single cloud with the openstack CLI e.g. `OS_CLOUD=omedev openstack server list`, but it's ignored by the `shade.inventory` module. This adds it to the dynamic openstack inventories so it can be used with ansible.
E.g. `OS_CLOUD=omedev ansible-playbook -i inventory/openstack.py playbook.yml`
> Use OS_CLOUD env in dynamic inventory if set

- ansible/os-idr-playbooks/os-idr-create-example.yml
- ansible/roles/openstack-idr-instance/README.md
- ansible/roles/openstack-idr-instance/defaults/main.yml
- ansible/roles/openstack-idr-instance/tasks/main.yml
- ansible/roles/openstack-idr-keypairs/README.md
- ansible/roles/openstack-idr-keypairs/tasks/main.yml
- ansible/roles/openstack-idr-network/README.md
- ansible/roles/openstack-idr-network/defaults/main.yml
- ansible/roles/openstack-idr-network/tasks/main.yml
This contains the majority of the changes to the IDR specific roles from https://github.com/manics/infrastructure/tree/idr-0-3-0: `openstack-idr-{instance,keypair,network}`
> Openstack IDR roles (IDR-0.3.0)

- ansible/roles/network/README.md
- ansible/roles/network/tasks/add_basic_ifaces.yml
- ansible/roles/network/tasks/main.yml
- ansible/roles/network/templates/etc-sysconfig-network-scripts-ifcfg.j2
- Adds a tasks for adding a single NIC without any fancy configuration
- This was required because a full network restart was causing problems on one of the IDR instances. This addition should only be used where unavoidable.
- Allows the MTU to be unset (i.e. managed by the system).
> Network basic interface addition (IDR-0.3.0)

- ansible/roles/devspace/defaults/main.yml
This should include the bug fix for handling submodules in the OMERO build /cc @aleksandra-tarkowska
> Bump default devspace version to 0.3.4

- ansible/idr-playbooks/idr-dundee-nfs.yml
- ansible/idr-playbooks/idr-local-users.yml
- ansible/idr-playbooks/idr-omero.yml
- ansible/idr-playbooks/os-idr-volumes.yml
The current DIR hostgroup environment naming strategy:
- IDR production instances are in group `{{ idr_environment }}-*hosts`
- IDR analysis instances are in group `{{ idr_environment }}-a*hosts`
> IDR hostgroup naming (IDR-0.3.0)

- ansible/roles/omero-web-apps/README.md
- ansible/roles/omero-web-apps/tasks/main.yml
The tuples that go into `omero.web.ui.top_links` are a bit of a mystery at first. This PR modifies the `omero-web-apps` role so that each of the tuple elements is named.
These field names are based on the code in https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroWeb/omeroweb/webclient/decorators.py#L162 (I couldn't find any other docs)
> Name fields in `omero.web.ui.top_links` (omero-web-apps role) (IDR-0.3.0)

- ansible/idr-playbooks/idr-ebi-nfs.yml
This includes adding `nolock` to the NFS mount options (not sure why it's required, but it failed without it), and using a modified network role to setup the second NIC.
> Fix the EBI NFS playbook (IDR-0.3.0)

- ansible/inventory/openstack-private.py
Use optional metadata properties on OpenStack instances to:
1. Automatically set an SSH proxy host
- If the env-var `OS_PROXY_DISCOVER=1` and property `ssh_proxy_host` is set on the instance:
- `ssh_proxy_host=proxy` indicates this instance should be used as a SSH proxy for any instances connected to the same network
- `ssh_proxy_host=required` means attempt to find an instance on the same network with `ssh_proxy_host=proxy` and if found set the host-variable `ansible_ssh_common_args` with `ProxyCommand`, unless that hostvar already has a value.
- The env-var is required to avoid surprising people who use this dynamic inventory without being aware of the extra features.
2. Return networks in the original order
- The OpenStack dynamic inventory returns the list of networks that an instance …
> Openstack dynamic inventory: store and detect SSH proxy (IDR-0.3.0)

- ansible/idr-playbooks/idr-local-users.yml
Minor cleanup, the management VM is in `{{ idr_environment }}-hosts` so doesn't need to be specified separately.
> Remove non-specific management-hosts from idr-local-users.yml (IDR-0.3.0)

- ansible/roles/devspace/tasks/devspace-install.yml
Last release seems to have broken docker-py /cc @joshmoore @aleksandra-tarkowska 
See https://github.com/ansible/ansible-modules-core/issues/5775 and
https://github.com/kennethreitz/requests/issues/3734 for the relevant issues
> Cap requests version below 2.12.2

- ansible/Vagrantfile
- ansible/roles/nginx/README.md
- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/files/nginx-mainline.repo
- ansible/roles/nginx/tasks/main.yml
- ansible/tests/nginx-mainline.yml
- ansible/tests/nginx.yml
Adds a variable to setup Nginx mainline (currently 1.11) instead of the default stable (1.10). This does not support switching between these two repositories on an existing Nginx server.
The new IDR caching config requires support for complex maps which requires Nginx 1.11.
> nginx role can optionally setup mainline instead of stable repo (IDR-0.3.1)

- ansible/roles/nginx-proxy/README.md
- ansible/roles/nginx-proxy/defaults/main.yml
- ansible/roles/nginx-proxy/templates/nginx-confd-proxy-cache.j2
- ansible/roles/nginx-proxy/templates/nginx-confd-proxy.j2
Adds a parameter to optionally modify the cache-key based on a regex-match.
This is required for the new IDR caching config.
Running this on an existing server will result in a configuration change, but there should be no functional difference (it'll create a map with a single default value which is equivalent to using that value directly).
> Add optional nginx_proxy_cache_key_map for modifying cache key (IDR-0.3.1)

- ansible/idr-playbooks/group_vars/proxy-hosts.yml
https://github.com/openmicroscopy/openmicroscopy/pull/4985 disables client side caching of AJAX requests by adding `_=$TIMESTAMP` as a query parameter. This means we must ignore any query parameter of the form `_=\d+` when checking the cache.
--depends-on #207
--depends-on #208
> New IDR nginx caching config to ignore _=\d+ query param (IDR-0.3.1)

- ansible/roles-dev/hosts-populate/README.md
- ansible/roles-dev/hosts-populate/tasks/main.yml
- ansible/roles-dev/hosts-populate/templates/etc-hosts.j2
This role takes a list of openstack ansible groups, and populates `/etc/hosts` on a given server with the IPs and hostnames of all servers in those groups. It may also work for normal (non-openstack) groups too.
See #215 for an example
> Add role for managing /etc/hosts in openstack instances (IDR-0.3.1)

- ansible/idr-playbooks/idr-03-postinstall.yml
- ansible/idr-playbooks/idr-bastion.yml
This populates `/etc/hosts` on the IDR bastion servers with a list of hosts in the same idr-environment. This means you can `ssh` into the bastion server and connect to other hosts by hostname instead of having to lookup the IP.
e.g.
```
ssh -A `floating-ip-of-demoNN-bastion-host
ssh demoNN-omero
```
--depends-on #214
> Setup /etc/hosts on bastion hosts (IDR-0.3.1)

- ansible/idr-playbooks/idr-omero.yml
- ansible/roles/analysis-tools/tasks/main.yml
I've no idea why `analysis-tools` was installing `moreutils-parallel`. Changed to install `parallel` and this roles has been added to `idr-playbooks/idr-omero.yml`.
> Install parallel on IDR OMERO servers (IDR-0.3.1)

- ansible/roles/omero-python-deps/tasks/main.yml
The OMERO.server `metadata` plugin requires the YAML and Jinja2 python modules.
> Install jinja2 PyYAML in omero-python-deps (IDR-0.3.1)

- ansible/roles/openstack-idr-instance-network/README.md
- ansible/roles/openstack-idr-instance-network/tasks/main.yml
If you need to add a new network to an existing openstack instance you can use this role. This role only handles the openstack side of things, you will also need to configure your instance to use the additional network. If you only require very basic configuration use the role from https://github.com/openmicroscopy/infrastructure/pull/200
See the example in the README of this role.
> Add role for adding openstack networks to existing instances (IDR-0.3.1)

- ansible/roles/ice/tasks/main.yml
- ansible/roles/omero-web-runtime/tasks/main.yml
This works around a bug(?) in Ansible 2.2 involving complex pip requirements: https://github.com/ansible/ansible/issues/19321
This should allow most of the dependencies of the `omero-server` role to be installed, however there's another Ansible bug involving virtualenvs which means `omego` gets installed into the wrong place.
> Work around issues in Ansible 2.2

- .travis.yml
- README.md
- requirements.txt
While trying to initiate a VM on an OpenStack instance, I encountered https://groups.google.com/forum/#!msg/ansible-project/3pj7jknSqd8/cr4Zt6L2BQAJ.
Rather than hardcoding the version in various places in the documentation, this PR migrates all the Python dependencies into a top-level `requirements.txt` as we do for any Python app. Dependencies can be pinned and upgraded via PR.
Travis is also updated to consume the requirements file.
> Capture Ansible requirements in requirements.txt

- ansible/idr-playbooks/idr-reboot-if-kernel.yml
- ansible/roles-dev/reboot-server/README.md
- ansible/roles-dev/reboot-server/defaults/main.yml
- ansible/roles-dev/reboot-server/tasks/main.yml
- ansible/roles-dev/reboot-server/tasks/reboot-if-kernel-upgraded.yml
- ansible/roles-dev/reboot-server/tasks/reboot-server.yml
A development role for rebooting servers either if the kernel has been changed, or unconditionally, depending on the configuration options.
Also adds an IDR playbook for rebooting servers after a kernel upgrade.
Once this is stable it should replace the reboot tasks in `roles/upgrade-distpackages`.
This role/playbook are needed because rebooting servers behind a proxy host gets complicated if the proxy host also requires a reboot, since it'll lead to the unexpected interruption of a SSH connections to internal servers. This means it must be carefully ordered.
> Separate role to reboot server (IDR-0.3.1)

- ansible/idr-playbooks/idr-ebi-nfs.yml
- ansible/idr-playbooks/idr-proxy.yml
- ansible/idr-playbooks/idr-upgrade-dist.yml
- ansible/scripts/os-idr-snapshot.sh
- `management-hosts` shouldn't be referenced directly, it's already part of an idr-environment group
- `Changed a variable test so that the proxy can be automatically configured in the absence of an analysis platform`
- `Changed the EBI NFS mount options to allow auto-negotiation`
- Updated the `os-idr-snapshot.sh` script.
> Miscellaneous small IDR fixes (IDR-0.3.1)

- ansible/idr-playbooks/idr-00-preinstall.yml
- ansible/idr-playbooks/idr-networks.yml
Attempt to initialise all NICs before any other configuration is done.
This is important when using a bastion server on multiple networks, since by default only the first NIC is initialised, which would prevent internal hosts from being accessed via the uninitialised NIC.
> Initialise all NICs when multiple cloud networks are present (IDR-0.3.1)

- ansible/Vagrantfile
- ansible/roles/java/README.md
- ansible/roles/java/defaults/main.yml
- ansible/roles/java/tasks/main.yml
- ansible/tests/java.yml
- Use `_` in variable names
- Control JDK installation with a boolean instead of requiring a list of versions, since it probably makes sense for this to be the same as the JRE versions
This is a breaking change, but nothing is currently using these variables.
> Refactor java role (IDR-0.3.1)

- ansible/idr-playbooks/group_vars/omero-hosts.yml
Update the IDR playbooks to install `jstack` on the OMERO servers. This requires installing the JDK.
--depends-on https://github.com/openmicroscopy/infrastructure/pull/219
> Install JDK on idr OMERO for jstack (IDR-0.3.1)

- ansible/roles/nginx-proxy/templates/nginx-confd-proxy.j2
This is an attempt to make Nginx redirects relative to `host:port` instead of the default which is to use the `host` only. It didn't have the desired effect with OMERO.web, but it's been deployed anyway.
- http://nginx.org/en/docs/http/ngx_http_core_module.html#port_in_redirect
- http://nginx.org/en/docs/http/ngx_http_core_module.html#server_name_in_redirect
> Disable nginx port_in_redirect (IDR-0.3.1)

- ansible/os-devspace.yml
The previous modification to use m1.large was done in the context of testing the new installation as the m2.large VM was not available. In order to complete the OMERO jobs, a VM with larger RAM capacity is necessary.
> Revert VM used for devspace to m2.large

- ansible/roles/network-cloud-interfaces/files/dhcp-dhclient-enter-hooks
- ansible/roles/network-cloud-interfaces/tasks/main.yml
If a CentOS 7 cloud instance has multiple openstack DHCP interfaces the default gateway/route may end up on a random interface. This causes problems with external access if only one of the interfaces has a floating IP. This PR adds a client-side DHCP hook to disable all routes other than for `eth0`.
This is a dumb "do-the-right-thing" role for setting up cloud networks so it's not configurable. If you need something more complicated use the `network` role in combination with additional tasks for handling config.
> Disable all routes apart from eth0 in network-cloud-interfaces (IDR-0.3.2)

- ansible/idr-playbooks/idr-00-preinstall.yml
- ansible/idr-playbooks/idr-ebi-nfs.yml
- The post-kernel-upgrade reboot is handled in a separate playbook (not run by default)
- Multi-interface network config is handled in another playbook
> Demo32 cleanups (IDR-0.3.2)

- ansible/idr-playbooks/group_vars/omero-hosts.yml
- ansible/idr-playbooks/idr-01-install-idr.yml
- ansible/idr-playbooks/idr-downloads.yml
- ansible/idr-playbooks/idr-ebi-nfs.yml
- ansible/idr-playbooks/idr-networks.yml
- ansible/requirements.yml
Final changes for release:
- Set IDR OMERO.server nofile limit to `16384`
- Bump omero and map versions
- Fixes for when a full redeployment is run against an existing active server
- Initial setup or rsync server (the database dump will need to be manually created in `/srv/sql`)
Todo: Update tags in requirements.yml from:
~~`diff --git a/ansible/requirements.yml b/ansible/requirements.yml`~~
> IDR 0.3.2 updates for final release (IDR-0.3.2)

- ansible/idr-openstack-post.yml
The snapshotting scripts under ansible/scripts
depend on jq being installed locally.
> Add jq install to openstack post

- README.md
- ansible/README.md
- docs/README.md
- docs/ansible/contributing.md
- docs/ansible/installation.md
This PR is intended to perform a couple of different cleanups and additions to the READMEs and docs in this repository post-migration to galaxy including:
- Top-level `README` points to ansible (once), gpfs, openstack (once)
- `docs/README` points to each ansible (is this needed??)
- `docs/ansible/` has no README
- `ansible/README` points to `docs/ansible`
> Ansible readme

- ansible/hardware-dell/dell-update-fc630.yml
Updates  the `dell-update-fc630.yml` playbook with the latest versions of the BIOS and iDRAC. These can be deployed with `ansible-playbook -i <INVENTORY> hardware-dell/dell-update-fc630.yml -l <LIMIT-HOSTS> --ask-become-pass` and will involve an automatic reboot.
> Update Dell FC630 bios and idrac versions

- ansible/server-state-playbooks/nightshade-web/playbook.yml
Upgraded ns-web by re-running the `server-state-playbook` after bumping the OMERO.web version in the playbook.
Note, this did not work straight off, as the role which this playbook is using a hard-coded set of dependencies, rather than reading the `requirements.yml` shipped with the OMERO.web distribution. This will be fixed in the role with the inclusion of https://github.com/openmicroscopy/ansible-role-omero-web/pull/3/files
Run against ome-ns-web in check mode: [ns-web-531_upgrade-provision_20170426-164631Z.txt](https://github.com/openmicroscopy/infrastructure/files/962309/ns-web-531_upgrade-provision_20170426-164631Z.txt)
Run against ome-ns-web: [ns-web-531_upgrade-provision_20170426-164926Z.txt](https://github.com/openmicroscopy/infrastructure/files/962310/ns-web-531_upgrade-provision …
> ome-ns-web: Bumping OMERO.web release

- ansible/ome-analysis/ansible.cfg
- ansible/ome-analysis/initial.yml
- ansible/ome-analysis/ome-jupyter.yml
- ansible/ome-analysis/requirements.yml
A self-contained playbook for setting up JupyterHub on a physical host with a pre-existing LVM volume group. Also sets up cadvisor for container monitoring. `idr.connection` parameters are not configured by this playbook.
> Attempt to provision non-vm docker jupyterhub

- ansible/server-state-playbooks/ome-dundeeomero/README.txt
- ansible/server-state-playbooks/ome-dundeeomero/Vagrantfile
- ansible/server-state-playbooks/ome-dundeeomero/molecule.yml
- ansible/server-state-playbooks/ome-dundeeomero/playbook.yml
- ansible/server-state-playbooks/ome-dundeeomero/requirements.yml
- ansible/server-state-playbooks/ome-dundeeomero/templates/nginx-omero.conf.j2
- ansible/server-state-playbooks/ome-dundeeomero/tests/test_default.py
Ongoing development work for migration of Dundee's OMERO server at 5.3 driven (mostly) via Ansible.
After manual provisioning of `.vmdk` and manual creation of the PVs...  
```
LS27172:ome-dundeeomero kenny$ ansible-playbook --diff -l ome-dundeeomero-test.openmicroscopy.org  -i ~/forks/management_tools/ansible/inventory/vagrant-test playbook.yml  --ask-vault-pass --ask-become-pass --tags=lvm
```
```
[root@ome-dundeeomero-test ~]# lvs
LV      VG         Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
basedir omero      -wi-ao----  9.79g
pgdata  postgresql -wi-ao---- 73.50g
root    rhel       -wi-ao---- 13.39g
swap    rhel       -wi-ao----  1.60g
[root@ome-dundeeomero-test ~]# ls /opt/omero/
[root@ome-dundeeomero-test ~]# df -h /opt/omero/
Filesystem …
```
> ome-dundeeomero provisioning development PR 

- ansible/server-state-playbooks/nightshade-web/playbook.yml
- ansible/server-state-playbooks/ome-dundeeomero/playbook.yml
tested in infra-testpr - produces an upgraded OMERO.web 5.3.2 server.
> Nightshade 5.3.2 upgrade (ome-dundeeomero & ns-web)

- ansible/server-state-playbooks/nightshade-web/playbook.yml
- ansible/server-state-playbooks/nightshade-web/templates/omero-web-config-for-webapps.j2
- ansible/server-state-playbooks/ome-dundeeomero/playbook.yml
- ansible/server-state-playbooks/ome-dundeeomero/templates/nightly-pg_dump-omero.sh.j2
Next steps and cleanup for the New Nightshade server pair.
> ome-dundeeomero next steps / cleanup

- ansible/server-state-playbooks/nightshade-web/playbook.yml
- ansible/server-state-playbooks/nightshade-web/templates/omero-web-config-for-webapps.j2
- ansible/server-state-playbooks/ome-dundeeomero/playbook.yml
University of Dundee OMERO server ecosystem, known as "Nightshade", upgraded to 5.3.3, with the latest versions of the OMERO.web apps distributed via pypi.
Internal OME Trello card: https://trello.com/c/kW9gdajk/21-production-server-upgrades
>  ome-dundeeomero and nightshade-web to 5.3.3

- ansible/server-state-playbooks/ome-dundeeomero/playbook.yml
- ansible/server-state-playbooks/ome-dundeeomero/templates/nightly-pg_dump-omero.sh.j2
An update to address the fact that the nightly backup was failing, though testing at the shell was successful.
Check mode against `ome-dundeeomero`: [ansible_run-backup-script-CHECK-ome-dundeeomero_20170704-120625Z.txt](https://github.com/openmicroscopy/infrastructure/files/1121987/ansible_run-backup-script-CHECK-ome-dundeeomero_20170704-120625Z.txt)
Live run against `ome-dundeeomero`: [ansible_run-backup-script-UPDATE-ome-dundeeomero_20170704-120909Z.txt](https://github.com/openmicroscopy/infrastructure/files/1121988/ansible_run-backup-script-UPDATE-ome-dundeeomero_20170704-120909Z.txt)
Without this PR
```
[root@ome-dundeeomero cron.daily]# run-parts  /etc/cron.daily/ -v
[root@ome-dundeeomero cron.daily]# du -sh /backups/*
64K    /backups/nightly-pg_dump_omero.dir
```
With this PR
``` …
```
> ome-dundeeomero backup script Fix: can't use sudo from /etc/cron

- ansible/server-state-playbooks/www-dev/www-dev.yml
This PR follows up on #281 and addresses the issue captured in https://github.com/openmicroscopy/ansible-role-jekyll-build/issues/3 at the playbook level
The main problem is that `bundle` is not on the default `PATH` failing the `bundle install` handler in the `openmicroscopy.jekyll-build` role. This PR prepends `/usr/local/bin` to the PATH and adds the symlink step to the `jekyll` tag.
With this PR included, there should be no more need for the playbook to be executed twivewhen the Jekyll source code is changed. Additionally, the dependencies can be removed from the playbook and managed solely by the `Gemfile` of the source code and the `bundle install` handler.
To test this PR:
- from a reverted snapshot of the deployment Vm, run `ansible-playbook --ask-become-pass …
> www-dev: improve Jekyll redeployment

- ansible/ansible.cfg
If ara is not installed, this should produce no change in behavior.
If ara *is* installed, then all calls to `ansible-playbook` will be
recorded to an sqlite database in ~/.ara/.
If additionally, ARA_DATABASE is configured to point at a shared
database, then all runs of ansible-playbook will be centrally recorded.
> Ara: add plugin to default configuration

- ansible/server-state-playbooks/www-dev/tests/check_redirects.py
Test the redirects specified in `www-dev.yml`:
```
$ pytest check_redirects.py
============================= test session starts ==============================
platform darwin -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /Users/spli/work/web-new, inifile:
collected 21 items
check_redirects.py .....................
```
Set `HOST` to the test server.
> Add test script for web-dev redirects

- ansible/server-state-playbooks/www/requirements.yml
This version contains the improvements allowing to use multiple configuration
files and should be required for deploying the website.
> Consume 1.2.0 version of the jekyll-build role

- ansible/server-state-playbooks/www/www.yml
Requires: https://github.com/openmicroscopy/ansible-role-nginx-proxy/pull/10 
Specific to the QA app, uploading a 2G file, the uploader doesn't send 2G to `ome-www(-dev)` straight away, but the first request seems to contain the request size of the total upload, which `ome-www(-dev)` instantly writes an error log message, then follows up to the client after 30s with `HTTP Error 413 Request entity too large`. 
This seems to fix this behaviour.
> 2g max body size for QA

- ansible/requirements-compat.yml
- ansible/requirements.yml
While the PG role undergoes a few milestones for
the new 3.0 version, pin all requirements to the
latest stable, 2.0.0.
See https://github.com/openmicroscopy/ansible-role-postgresql/pull/6
> Pin openmicroscopy.postgresql to 2.0.0

- ansible/server-state-playbooks/www/tests/check_redirects.py
- ansible/server-state-playbooks/www/www.yml
This PR contains the necessary playbook adjustements as well as tests updating the OME Website redirects for the new security advisories pages:
- https://www.openmicroscopy.org/security/
- https://www.openmicroscopy.org/security/advisories/
- https://www.openmicroscopy.org/security/advisories/2012-SV1-ldap-authentication/
- https://www.openmicroscopy.org/security/advisories/2014-SV1-unicode-passwords/
- https://www.openmicroscopy.org/security/advisories/2014-SV2-empty-passwords/
- https://www.openmicroscopy.org/security/advisories/2014-SV3-csrf/
- https://www.openmicroscopy.org/security/advisories/2014-SV4-poodle/
- https://www.openmicroscopy.org/security/advisories/2016-SV1-cleanse/
- https://www.openmicroscopy.org/security/advisories/2016-SV2-share/
- …
> Security redirects

- ansible/roles/sphinx-build/tasks/main.yml
See https://trello.com/c/ccx2knE7/68-check-whether-sphinx-can-be-upgraded-for-all-docs-jobs
> Update Sphinx version to 1.6.3

- ansible/ci-deployment.yml
- ansible/roles/jenkinsslave/meta/main.yml
- ansible/roles/omero-build/meta/main.yml
- ansible/roles/omero-runtime/meta/main.yml
Companion PR to https://github.com/openmicroscopy/infrastructure/pull/307
While trying to deploy the Sphinx changes on the ci-docs nodes, I encountered execution issues while trying to execute the ci-deloyment playbook.
This commit prefixes all roles installed via Galaxy with openmicroscopy. It also adds a tag to the Sphinx role as this was the only required change in that case.
> Prefix decoupled Ansible roles with openmicroscopy.

- ansible/roles/omero-build/tasks/main.yml
Use the latest version 6 of exe4j to support Java 9.
Test: Check Importer and/or Insight exe on Windows with Java 9 installed.
> Update exe4j version

- README.md
- docs/vmware/mac-image.md
Not much to review except for the top-level README link and a look over the content.
Mostly based on the older [Mac virtual machine setup](https://docs.google.com/document/d/14OlGJHVzf95yin3RESPcsTgAFgnrwnxl2FXvO9VNmeA/edit#) gdoc, updated for use with ansible and more recent versions of the MacOS X installer.
> docs: Add Mac VMware image creation page
