- .travis.yml
Closes https://github.com/openmicroscopy/infrastructure/issues/6
> Add Travis syntax check

- ansible/ci-deployment.yml
- ansible/roles/ice/README.md
- ansible/roles/ice/defaults/main.yml
- ansible/roles/ice/tasks/main.yml
- ansible/roles/ice/vars/ice-3.5.yml
- ansible/roles/ice/vars/ice-3.6.yml
This has already been run against cowfish.
> Add choice of either Ice 3.5 or 3.6

- ansible/roles/omero-build/tasks/main.yml
- ansible/roles/omero-build/templates/cmake-path.sh.j2
> cmake 3.3.2

- ansible/roles/docker-dns-client/README.md
- ansible/roles/docker-dns-client/defaults/main.yml
- ansible/roles/docker-dns-server/README.md
- ansible/roles/docker-dns-server/defaults/main.yml
- ansible/roles/network/README.md
> Network and Docker DNS READMEs and defaults

- ansible/idr-deployment.yml
- ansible/roles/system-monitor-agent/README.md
- ansible/roles/system-monitor-agent/tasks/main.yml
Currently only narwhal, orca will have to wait for #21
> Install check-mk

- ansible/idr-deployment.yml
- ansible/idr-provision.yml
- ansible/roles/debug-dumpallvars/README.md
- ansible/roles/debug-dumpallvars/defaults/main.yml
- ansible/roles/debug-dumpallvars/tasks/main.yml
- ansible/roles/debug-dumpallvars/templates/dumpall.j2
- ansible/roles/docker-dns-client/tasks/main.yml
- ansible/roles/docker-dns-server/tasks/main.yml
- ansible/roles/docker-storage/tasks/main.yml
- ansible/roles/lvm-partition/tasks/main.yml
- ansible/roles/upgrade-distpackages/README.md
- ansible/roles/upgrade-distpackages/defaults/main.yml
- ansible/roles/upgrade-distpackages/tasks/main.yml
Changes/additions made whilst provisioning orca
> Orca changes/fixes

- ansible/idr-services.yml
- ansible/roles/nginx-proxy/README.md
- ansible/roles/nginx-proxy/defaults/main.yml
- ansible/roles/nginx-proxy/handlers/main.yml
- ansible/roles/nginx-proxy/tasks/main.yml
- ansible/roles/nginx-proxy/templates/nginx-conf.j2
- ansible/roles/nginx-proxy/templates/nginx-confd-dynamic-proxy.j2
This is for configuring `web-proxy` (I've bagsied it for the IDR)
> Nginx proxy role

- ansible/ci-provision.yml
- ansible/roles/jenkinsslave/tasks/main.yml
- ansible/roles/jenkinsslave/tasks/setup_virtualenv.yml
> Jenkinsslave improvements

- ansible/qa-web-deployment.yml
- ansible/roles/python-devel/tasks/main.yml
> installing python-devel

- ansible/qa-web-deployment.yml
- ansible/roles/openldap-devel/tasks/main.yml
- ansible/roles/python-devel/tasks/main.yml
trying to fix https://ci.openmicroscopy.org/view/Mgmt/job/REGISTRY-merge-deploy/17/console
> installing openldap-devel

- ansible/ci-provision.yml
Tell me where to put it (prod playbook file?) and I'll move it.
> Add playbook for minke

- ansible/roles/basedeps/tasks/main.yml
> Install LSB core package on all nodes

- ansible/all-upgrade.yml
Runs `yum update` on all hosts in the inventory (`all` is an ansible keyword meaning all hosts).
> Add playbook for simple upgrades of distro packages

- README.md
- docs/ansible.md
- docs/contributing.md
- docs/example_workflows.md
Some docs for discussion in next week's sysadmin/infrastructure/omero-deploy/docker meeting
> Add some initial documentation for ansible

- ansible/idr-openstack-post.yml
- ansible/idr-openstack-pre.yml
- ansible/idr-openstack.yml
- ansible/roles/network/tasks/main.yml
- ansible/roles/network/templates/etc-sysconfig-network-scripts-ifcfg.j2
- ansible/roles/openstack-prepare/README.md
- ansible/roles/openstack-prepare/handlers/main.yml
- ansible/roles/openstack-prepare/tasks/main.yml
- openstack/idr-openstack-setup-tenant.sh
- openstack/idr-openstack-using.md
- openstack/idr-openstack.md
Contains some roles and changes to help with setting up OpenStack hypervisor nodes. Also some docs on setting up and using OpenStack.
> Openstack installation helpers and docs

- ansible/idr-nfs-hosts.yml
- ansible/roles/nfs-share/README.md
- ansible/roles/nfs-share/defaults/main.yml
- ansible/roles/nfs-share/handlers/main.yml
- ansible/roles/nfs-share/tasks/main.yml
- ansible/roles/nfs-share/templates/exports.j2
Old style NFS (no authentication)
There's a bug with the current NFS package which means you may error messages in the logs, and there may be delays when you first access a file https://bugzilla.redhat.com/show_bug.cgi?id=1285097
> Add NFS server shares role

- ansible/idr-docker-localstorage.yml
- Increase `/var/log` LV size
- Add `system-monitor-agent` role
> Resize /var/log and add check-mk on idr-docker-localstorage

- ansible/roles/nginx-proxy/handlers/main.yml
- ansible/roles/nginx-proxy/tasks/main.yml
#72 requires more work, so opening this to get the fix in sooner.
> Nginx proxy state typo

- ansible/all-initial.yml
- ansible/ci-provision.yml
- ansible/idr-services.yml
- ansible/os-create.yml
- ansible/os-volumes.yml
- Change ci-initial.yml to ansible/all-initial.yml, and apply to `all`, so it can be used for setting up any new server.
- Change `idr-services.yml` to expand root and log volumes
> Web proxy setup

- ansible/roles/dell-update/README.md
- ansible/roles/dell-update/tasks/main.yml
We've got enough identical servers that's it worth automating server updates. See example playbook in README.
@kennethgillen
> Role for running Dell updates

- ansible/idr-docker-localstorage.yml
> Add versioncontrol-utils to idr-docker-localstorage

- ansible/idr-docker-localstorage.yml
- ansible/idr-openstack-post.yml
- ansible/roles/logrotate/README.md
- ansible/roles/logrotate/defaults/main.yml
- ansible/roles/logrotate/tasks/main.yml
- ansible/roles/logrotate/templates/logrotate.conf.j2
Still needs deployment/testing
> Add custom logrotate config

- ansible/idr-playbooks/idr-monitoring.yml
- ansible/os-idr-ebi.yml
- ansible/os-idr-uod.yml
- ansible/roles/omero-logmonitor/README.md
- ansible/roles/omero-logmonitor/defaults/main.yml
- ansible/roles/omero-logmonitor/tasks/main.yml
- ansible/roles/omero-logmonitor/templates/omero-fenton-cfg.j2
- ansible/roles/omero-logmonitor/templates/systemd-system-omero-logmonitor-service.j2
Switch the logbot to use slack instead of jabber
> Logmonitor slack

- ansible/ci-jenkins-linux.yml
Pretty self explanatory. See corresponding private config.
> Add sudoers role to ci-jenkins-linux

- ansible/os-uod-slave.yml
- ansible/uod-slave.yml
* decrease the size of the image to medium;
small would possibly be better if ci-omero is removed
* change the ordering of docker imports;
the docker mount though is *still* not being mounted
> spiders: small modifications

- ansible/jekyll-playbooks/jekyll-deploy.yml
- ansible/jekyll-playbooks/jekyll-install.yml
- ansible/jekyll-playbooks/templates/www-nginx.j2
- ansible/uod-web.yml
For example:
```
ansible-playbook -i inventory uod-web.yml -l www-dev -e dev_site_account=joshmoore -e dev_site_branch=master  -t quickdeploy
```
> uod-web: enable configurable re-deployments

- ansible/ci-deployment.yml
- ansible/ci-jenkins-linux.yml
- ansible/roles/omero-build/tasks/main.yml
Improvements to the ci provision and deployment code, updated when adding a new OME ci slave. https://github.com/openmicroscopy/management_tools/pull/197
> New seabass provision forced improvements

- ansible/ci-deployment.yml
- ansible/roles/ansible/README.tmd
- ansible/roles/ansible/tasks/main.yml
- ansible/roles/jenkinsslave/tasks/setup_virtualenv.yml
add missing package(s):
- add `Pygments`, doc prerequisites
- add `ansible`, omeroweb-install prerequisites
see https://ci.openmicroscopy.org/job/TEST-DEV-merge-docs and https://ci.openmicroscopy.org/job/TEST-DEV-merge-docs-autogen
keep in mind https://github.com/openmicroscopy/infrastructure/pull/20
> Improve doc ci node

- ansible/devspace-runtime.yml
- ansible/devspace.yml
- ansible/os-devspace.yml
- ansible/os-uod-slave.yml
- ansible/roles/devspace/defaults/main.yml
- ansible/roles/devspace/tasks/main.yml
- ansible/roles/jenkinsslave/defaults/main.yml
This PR is an addition to #114 that allow you to hide jenkins behind password. That was raised by @kennethgillen.
Test the same as #114, but either you will be asked for password or set Username and Passwrod like
```
(dev) ansible-playbook -i /path/to/inventory/devspace -u centos devspace.yml -e jenkins_nginx_password=secret
```
`jenkins_nginx_password` & `jenkins_nginx_username (default devspace)`
> prompt for jenkins password

- ansible/roles/postgresql/vars/main.yml
The rpms containing the postgres yum repo configurations have changed.
> Postgres yum repo rpms have been updated

- ansible/idr-playbooks/idr-omero.yml
- ansible/roles/nginx-proxy/vars/example-omero.yml
nginx cache for web api and mapr cache
> add api and mapr to nginx cache

- ansible/roles/nginx-proxy/README.md
- ansible/roles/nginx-proxy/defaults/main.yml
- ansible/roles/nginx-proxy/files/nginx-confd-proxy-websockets.conf
- ansible/roles/nginx-proxy/tasks/main.yml
- ansible/roles/nginx-proxy/tasks/nginx-selinux.yml
- ansible/roles/nginx-proxy/tasks/nginx-ssl-certs.yml
- ansible/roles/nginx-proxy/tasks/nginx-streams.yml
- ansible/roles/nginx-proxy/tasks/nginx-websockets.yml
- ansible/roles/nginx-proxy/templates/nginx-conf.j2
- ansible/roles/nginx-proxy/templates/nginx-confd-proxy.j2
- ansible/roles/nginx-proxy/templates/nginx-confd-streams.j2
Add variables and template config to nginx-proxy role for proxying websockets (required by jupyterhub)
> Handle websockets and allow streaming in nginx proxy

- ansible/roles/devspace/defaults/main.yml
Follow up - https://github.com/openmicroscopy/devspace/pull/55
> bump devspace version

- ansible/Vagrantfile
Fix a bug reported in https://github.com/openmicroscopy/infrastructure/pull/165#pullrequestreview-8576264
> Only override vagrant ssh user for openstack provider

- ansible/idr-playbooks/group_vars/proxy-hosts.yml
- ansible/roles/nginx-proxy/README.md
- ansible/roles/nginx-proxy/templates/nginx-confd-proxy-cache.j2
This PR should prevent proxy cache from running out of space. Assuming cache volume is 100GB calculation done in https://trello.com/c/r9yTDj0y/82-outage#comment-582ee489a678bf8e6aa742dc
cc: @joshmoore @manics @eleanorwilliams
> update proxy cache sizes and set upper limit

- ansible/roles/basedeps/tasks/main.yml
- ansible/roles/omero-python-deps/tasks/pypi.yml
> remove gcc from basedeps

- ansible/devspace.yml
- ansible/roles/devspace/defaults/main.yml
this removes need of setting up `devspace_openstack_host` and clarify password message
cc: @jburel @sbesson
> set devspace_openstack_ip from ansible_host

- ansible/os-idr-playbooks/os-idr-ansible-command-helper.yml
Figures out the ansible-playbook command to run when deploying the IDR for the first time.
> The IDR ansible command helper (IDR-0.3.0)

- ansible/idr-playbooks/group_vars/dockermanager-hosts.yml
- ansible/idr-playbooks/group_vars/omero-hosts.yml
- ansible/idr-playbooks/idr-docker.yml
This should be the latest tagged components in IDR-0.3.0
> Bump IDR tags (IDR-0.3.0)

- ansible/requirements.yml
Sets the version in requirements.yml
> Use tagged munin and munin-node roles

- ansible/Vagrantfile
- ansible/requirements.yml
- ansible/tests/haproxy.yml
Rebased from https://github.com/openmicroscopy/infrastructure/pull/199 (re-opening wasn't possible).
> Add haproxy to requirements.yml, add test (IDR-0.3.1) 

- ansible/roles/cli-utils/tasks/main.yml
See https://trello.com/c/n376kRC6/70-minor-deployment-issues
> Include bzip2 in cli-utils (IDR-0.3.1)

- ansible/idr-openstack-post.yml
- ansible/idr-openstack-pre.yml
- ansible/roles/gpfs/README.md
- ansible/roles/gpfs/defaults/main.yml
- ansible/roles/gpfs/tasks/gpfs-repoinstall.yml
- ansible/roles/gpfs/templates/gpfs-repo.j2
- ansible/roles/openstack-prepare/tasks/main.yml
Updates to roles whilst re-installing openstack
> Openstack re-installation

- ansible/os-devspace.yml
- ansible/os-idr-playbooks/os-idr-create-example.yml
- ansible/os-uod-docker.yml
- ansible/os-uod-web.yml
- ansible/uod-slave.yml
While testing the new OpenStack installation /cc @joshmoore @manics
> Use unversioned CentOS image

- ansible/idr-playbooks/group_vars/dockermanager-hosts.yml
- ansible/idr-playbooks/group_vars/omero-hosts.yml
Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD
> Bump IDR omero to 0.3.1-rc2, and idr-notebooks to HEAD (IDR-0.3.1)

- ansible/idr-playbooks/files/IDR-OMERO-52-omero.j2
- ansible/idr-playbooks/group_vars/omero-hosts.yml
- ansible/roles/omero-web-apps/tasks/main.yml
~~This includes https://github.com/openmicroscopy/infrastructure/pull/220 to avoid conflicts when cherry-picking.~~
> Update omero-web-apps role, update mapr (IDR-0.3.1)

- ansible/Vagrantfile
- ansible/ci-deployment.yml
- ansible/roles/omero-web-apps-build-dependencies/README.md
- ansible/roles/omero-web-apps-build-dependencies/tasks/main.yml
- ansible/roles/omero-web-apps-build-dependencies/tasks/redhat.yml
- ansible/test.yml
Add role to install node and grunt-cli
I have added the main and an redhat yml files
planning to add when things are sorted a debian one (in another PR)
> web app build role

- ansible/os-devspace.yml
> revert ram

- ansible/requirements.yml
> bump devspace role version

- ansible/requirements-internal.yml
Switch to the openmicroscopy tagged role (https://github.com/openmicroscopy/ansible-role-system-monitor-agent/pull/1)
> Switch to official tagged system-monitor-agent role

- ansible/server-state-playbooks/nightshade-web/playbook.yml
Updating the NGINX workers config to leave more room for WSGI.
Requires private config too: https://github.com/openmicroscopy/management_tools/pull/375
> Ns web perf config update

- ansible/server-state-playbooks/nightshade-web/playbook.yml
- ansible/server-state-playbooks/nightshade-web/templates/omero-web-config-for-webapps.j2
Tested on infra-testpr (connecting to eel), with success.
```
PLAY RECAP *********************************************************************
infra-testpr.openmicroscopy.org : ok=65   changed=11   unreachable=0    failed=0
```
[infra-testpr_ns-web_to_530.txt](https://github.com/openmicroscopy/infrastructure/files/919519/infra-testpr_ns-web_to_530.txt)
REQUIRES: https://github.com/openmicroscopy/management_tools/pull/373
> ns-web-vm removal of tagging & upgrade to 5.3.0

- ansible/idrsystems-playbooks/requirements.yml
- ansible/requirements.yml
See:
* https://github.com/openmicroscopy/infrastructure/pull/257
* https://github.com/IDR/idr-metadata/pull/237
> Bump version of celery-docker

- README.md
- docs/openstack/freebsd-image.md
- docs/openstack/local-setup.md
- docs/openstack/windows-image.md
Add instructions for creating and uploading OpenStack images for FreeBSD and Windows.
> docs: Add image creation instructions

- ansible/ome-analysis/ome-jupyter.yml
Updates for IDR 0.4.0 against ome2017 clone at UoD. Based on OMERO 5.3.
See:
* https://github.com/IDR/jupyter-docker/commit/5c654b2aad2d012c4918c5a21d794f431bb0039b (pushed to develop)
* https://github.com/openmicroscopy/bioformats/pull/2840
> IDR: 0.4.0 (for ome2017)

- ansible/server-state-playbooks/www-dev/README.txt
- ansible/server-state-playbooks/www-dev/Vagrantfile
- ansible/server-state-playbooks/www-dev/requirements.yml
- ansible/server-state-playbooks/www-dev/templates/www-dev.openmicroscopy.org.conf.j2
- ansible/server-state-playbooks/www-dev/www-dev.yml
Development of a new web server for OME website migration.
Private config in https://github.com/openmicroscopy/management_tools/pull/474
> Initial www-dev playbook

- ansible/server-state-playbooks/www-dev/templates/www-dev.openmicroscopy.org.conf.j2
- ansible/server-state-playbooks/www-dev/www-dev.yml
This PR to include next steps for www-dev nginx config
> www-dev_next-steps

- ansible/server-state-playbooks/www-dev/requirements.yml
- ansible/server-state-playbooks/www-dev/www-dev.yml
This PR should:
- use the latest released roles instead of custom branches
- consume the merge code for testing analytics /cc @joshmoore 
- uses the 404 page to handle undefined redirects
- add a new set of missing redirects reported during testing /cc @pwalczysko
> Website: second round of redirects

- ansible/requirements.yml
- ansible/server-state-playbooks/www/requirements.yml
- ansible/server-state-playbooks/www/www.yml
updates to resize the LVM lvs and filesystems
also configured jekyll-build with a site name
> ome-www deployment updates

- ansible/server-state-playbooks/www/requirements.yml
Bump of requirements to use the new role, required by this version the playbook.
> (www) Bump requirements for required update to role

- ansible/requirements.yml
- ansible/server-state-playbooks/www/requirements.yml
See https://github.com/openmicroscopy/ansible-role-jekyll-build/pull/9
> Bump the jekyll-build role to 1.2.1

- ansible/ci-deployment.yml
- ansible/roles/devtoolset-4/README.md
- ansible/roles/devtoolset-4/tasks/main.yml
For installing devtoolset-4 on cowfish.
> ci-linux-jenkins: Install devtoolset-4

- docs/storage/gpfs.md
> Update gpfs doc with mmnfs for ces share management
